#!/bin/bash

/pnpdata/hwpdesire/hwpdesire.sh -a 2100000
/pnpdata/hwpdesire/hwpdesire.sh -m 2100000



        # disable C1E, C3, C6
        cpupower idle-set -e 0
        cpupower idle-set -e 1
        cpupower idle-set -d 2
        cpupower idle-set -d 3
#       cpupower idle-set -d 4
